version: '3'
services:
  snce-group:
    build: .
    container_name: snce-app
    ports:
      - "8080:8080"
  mysql:
    image: "mysql:5"
    container_name: snce-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - "3306"
      - "33060"
    expose:
      - "3306"
      - "33060"
